import './globals.css'
import Link from 'next/link'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog App',
  description: 'Generated by next blog app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const header = (
    <header>
      <div className='text-center bg-slate-800 p-8 my-8 rounded-md'>
        <Link href='/'>
          <h1 className='text-2xl text-white font-bold mt-4'>Ninja's Blog</h1>
        </Link>
        <p className='text-slate-300'>Welcome to my developing blogs</p>
        <br />
      </div>
    </header>
  );

  const footer = (
    <footer>
      <div className='border-t border-slate-500 text-slate-400 mt-12 py-6 text-center'>
        <h3>Developed by Arch Patel</h3>
      </div>
    </footer>
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='mx-auto  max-w-2xl px-6'>
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  )
}



